/**
 * Unified Analytics export — scoped V2 fragments with Plus fallback when V2 is off.
 */

import "server-only";

import type {
  AnalyticsCompareBaseline,
  AnalyticsRangePreset,
} from "@/lib/analytics-date-range";
import {
  parseAnalyticsCompareBaseline,
  parseAnalyticsRangePreset,
  resolveAnalyticsDateRange,
} from "@/lib/analytics-date-range";
import { runAnalyticsEngine } from "@/lib/analytics-engine";
import { loadAnalyticsExportBundle } from "@/lib/analytics-export-data";
import {
  buildFilename,
  composeCsv,
  composeHtmlDocument,
  composeMarkdown,
  mimeFor,
  slugifyName,
} from "@/lib/analytics-export-format";
import type {
  AnalyticsExportFormat,
  AnalyticsExportResult,
  AnalyticsExportScope,
} from "@/lib/analytics-export-types";
import {
  getPartnerPlusAnalytics,
  getPartnerPlusCourseAnalytics,
  partnerPlusReportToCsv,
  partnerPlusReportToHtml,
  partnerPlusReportToMarkdown,
} from "@/lib/partner-analytics";

export type {
  AnalyticsExportFormat,
  AnalyticsExportResult,
  AnalyticsExportScope,
};

async function buildLegacyPlusExport(input: {
  productId: string;
  rangePreset: AnalyticsRangePreset;
  compareBaseline: AnalyticsCompareBaseline;
  format: AnalyticsExportFormat;
}): Promise<AnalyticsExportResult | null> {
  const range = resolveAnalyticsDateRange(input.rangePreset);

  const engine = await runAnalyticsEngine({
    productId: input.productId,
    preset: input.rangePreset,
    compare: input.compareBaseline,
  });
  if (!engine) return null;

  const plusShaped = await getPartnerPlusAnalytics(input.productId, range);
  if (!plusShaped) return null;

  const withInsights = {
    ...plusShaped,
    insights: engine.recommendations.map((r) => r.rationale),
  };

  const courseDetails = await Promise.all(
    plusShaped.courses.map((c) =>
      getPartnerPlusCourseAnalytics(input.productId, c.courseId, range)
    )
  );
  const validCourses = courseDetails.filter(
    (c): c is NonNullable<typeof c> => c !== null
  );

  const slug = slugifyName(engine.productName);
  const preset = input.rangePreset;
  const format = input.format;

  if (format === "csv") {
    return {
      content: partnerPlusReportToCsv(withInsights),
      filename: `arcademy-analytics-${slug || "project"}-${preset}.csv`,
      mimeType: "text/csv;charset=utf-8",
    };
  }
  if (format === "html") {
    return {
      content: partnerPlusReportToHtml(withInsights, validCourses),
      filename: `arcademy-analytics-${slug || "project"}-${preset}.html`,
      mimeType: "text/html;charset=utf-8",
    };
  }
  return {
    content: partnerPlusReportToMarkdown(withInsights, validCourses),
    filename: `arcademy-analytics-${slug || "project"}-${preset}.md`,
    mimeType: "text/markdown;charset=utf-8",
  };
}

/**
 * Build export payload from scoped V2 section serializers (or Plus when V2 off).
 */
export async function buildAnalyticsExport(input: {
  productId: string;
  rangePreset?: string;
  compareBaseline?: string;
  format: AnalyticsExportFormat;
  scope?: AnalyticsExportScope;
  courseId?: string;
}): Promise<AnalyticsExportResult | null> {
  const preset = parseAnalyticsRangePreset(input.rangePreset);
  const compare = parseAnalyticsCompareBaseline(input.compareBaseline);
  const scope: AnalyticsExportScope = input.scope ?? "full";

  const bundle = await loadAnalyticsExportBundle({
    productId: input.productId,
    scope,
    rangePreset: preset,
    compareBaseline: compare,
    courseId: input.courseId,
  });
  if (!bundle) return null;

  if (!bundle.v2Enabled) {
    return buildLegacyPlusExport({
      productId: input.productId,
      rangePreset: preset,
      compareBaseline: compare,
      format: input.format,
    });
  }

  const meta = {
    productId: input.productId,
    productName: bundle.productName,
    rangeLabel: bundle.rangeLabel,
    rangePreset: preset,
    compareBaseline: compare,
    generatedAt: new Date().toISOString().slice(0, 10),
    scope,
  };

  const content =
    input.format === "csv"
      ? composeCsv(meta, bundle.fragments)
      : input.format === "html"
        ? composeHtmlDocument(meta, bundle.fragments)
        : composeMarkdown(meta, bundle.fragments);

  return {
    content,
    filename: buildFilename(meta, input.format),
    mimeType: mimeFor(input.format),
  };
}

/** Staff intake markdown — full V2 pack (or Plus) with staff footer. */
export async function buildStaffPartnerReportMarkdown(
  productId: string
): Promise<{ markdown: string; filename: string } | null> {
  const result = await buildAnalyticsExport({
    productId,
    rangePreset: "all",
    compareBaseline: "none",
    format: "markdown",
    scope: "full",
  });
  if (!result) return null;

  const markdown = `${result.content}

---

_This report was generated by Arcademy staff from the Analytics engine export._
`;

  return {
    markdown,
    filename: result.filename.replace(
      /\.md$/,
      `-staff-${new Date().toISOString().slice(0, 10)}.md`
    ),
  };
}

export type { AnalyticsRangePreset, AnalyticsCompareBaseline };
