/**
 * Unified Analytics export — single code path for partner + staff exports.
 * Uses engine DTOs; no divergence from dashboard metrics.
 */

import "server-only";

import type { AnalyticsCompareBaseline, AnalyticsRangePreset } from "@/lib/analytics-date-range";
import {
  parseAnalyticsCompareBaseline,
  parseAnalyticsRangePreset,
  resolveAnalyticsDateRange,
} from "@/lib/analytics-date-range";
import { runAnalyticsEngine } from "@/lib/analytics-engine";
import {
  getPartnerPlusCourseAnalytics,
  getPartnerPlusAnalytics,
  partnerPlusReportToCsv,
  partnerPlusReportToHtml,
  partnerPlusReportToMarkdown,
} from "@/lib/partner-analytics";

export type AnalyticsExportFormat = "markdown" | "csv" | "html";

export type AnalyticsExportResult = {
  content: string;
  filename: string;
  mimeType: string;
};

function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
}

/**
 * Build export payload from the same engine + Plus serializers as Analytics UI.
 */
export async function buildAnalyticsExport(input: {
  productId: string;
  rangePreset?: string;
  compareBaseline?: string;
  format: AnalyticsExportFormat;
}): Promise<AnalyticsExportResult | null> {
  const preset = parseAnalyticsRangePreset(input.rangePreset);
  const compare = parseAnalyticsCompareBaseline(input.compareBaseline);
  const range = resolveAnalyticsDateRange(preset);

  const engine = await runAnalyticsEngine({
    productId: input.productId,
    preset,
    compare,
  });
  if (!engine) return null;

  const plusShaped = await getPartnerPlusAnalytics(input.productId, range);
  if (!plusShaped) return null;

  const withInsights = {
    ...plusShaped,
    insights: engine.recommendations.map((r) => r.rationale),
  };

  const courseDetails = await Promise.all(
    plusShaped.courses.map((c) =>
      getPartnerPlusCourseAnalytics(input.productId, c.courseId, range)
    )
  );
  const validCourses = courseDetails.filter(
    (c): c is NonNullable<typeof c> => c !== null
  );

  const slug = slugifyName(engine.productName);
  const date = new Date().toISOString().slice(0, 10);
  const format = input.format;

  if (format === "csv") {
    return {
      content: partnerPlusReportToCsv(withInsights),
      filename: `arcademy-analytics-${slug || "project"}-${preset}.csv`,
      mimeType: "text/csv;charset=utf-8",
    };
  }
  if (format === "html") {
    return {
      content: partnerPlusReportToHtml(withInsights, validCourses),
      filename: `arcademy-analytics-${slug || "project"}-${preset}.html`,
      mimeType: "text/html;charset=utf-8",
    };
  }
  return {
    content: partnerPlusReportToMarkdown(withInsights, validCourses),
    filename: `arcademy-analytics-${slug || "project"}-${preset}.md`,
    mimeType: "text/markdown;charset=utf-8",
  };
}

/** Staff intake markdown — engine-backed summary with staff footer. */
export async function buildStaffPartnerReportMarkdown(
  productId: string
): Promise<{ markdown: string; filename: string } | null> {
  const result = await buildAnalyticsExport({
    productId,
    rangePreset: "all",
    compareBaseline: "none",
    format: "markdown",
  });
  if (!result) return null;

  const markdown = `${result.content}

---

_This report was generated by Arcademy staff from the Analytics engine export._
`;

  return {
    markdown,
    filename: result.filename.replace(/\.md$/, `-staff-${new Date().toISOString().slice(0, 10)}.md`),
  };
}

export type { AnalyticsRangePreset, AnalyticsCompareBaseline };
