import type { AnalyticsDateRange } from "@/lib/analytics-date-range";
import type { EcosystemOverview } from "@/lib/ecosystem-analytics";

/** "State of Ecosystem Onboarding" report — shareable with Arcium. */
export function ecosystemReportToMarkdown(
  overview: EcosystemOverview,
  range: AnalyticsDateRange
): string {
  const generatedAt = new Date().toISOString().slice(0, 10);

  const scorecardLines = overview.scorecard.map((entry) => {
    const status =
      entry.met === null ? "No data yet" : entry.met ? "On target" : "Below target";
    return `| ${entry.label} | ${entry.value} | ${entry.target} | ${status} |`;
  });

  const funnelLines = overview.funnel.map((step) => {
    const rate =
      step.rateFromPrevious != null ? `${step.rateFromPrevious}%` : "—";
    return `| ${step.label} | ${step.count} | ${rate} |`;
  });

  const productLines = overview.products.map((p) => {
    const rate = p.completionRate != null ? `${p.completionRate}%` : "—";
    return `| ${p.productName} | ${p.publishedCourses} | ${p.starts} | ${p.badgeAwards} | ${rate} |`;
  });

  const hotspotLines = overview.quizHotspots.map(
    (h) =>
      `- **${h.missRate}% missed** (${h.attemptCount} answers) — “${h.prompt}” · ${h.courseTitle}`
  );

  const cohorts = overview.cohorts;

  return `# State of Ecosystem Onboarding

Generated: ${generatedAt} · Period: ${range.label}
Produced by Arcademy — the learning layer for the Arcium ecosystem.

## Scorecard

| Metric | Value | Target | Status |
| --- | ---: | ---: | --- |
${scorecardLines.join("\n")}

## Onboarding funnel (${range.label})

| Step | Count | Conversion from previous |
| --- | ---: | ---: |
${funnelLines.join("\n")}

## Ecosystem projects

| Project | Published courses | Learners started | Badges awarded | Completion rate |
| --- | ---: | ---: | ---: | ---: |
${productLines.length > 0 ? productLines.join("\n") : "| _No published projects yet_ | — | — | — | — |"}

## Learner cohorts (all time)

- Wallet-connected learners: ${cohorts.walletConnectedLearners}
- Learners with course activity: ${cohorts.learnersWithProgress}
- Learners in more than one course: ${cohorts.multiCourseLearners}${
    cohorts.returnRate != null ? ` (${cohorts.returnRate}% return rate)` : ""
  }
- Learners holding at least one badge: ${cohorts.learnersWithBadge}
- Median time from first lesson to completion: ${
    cohorts.medianDaysToCompletion != null
      ? `${cohorts.medianDaysToCompletion} days`
      : "not enough data"
  }

## Where learners struggle

${hotspotLines.length > 0 ? hotspotLines.join("\n") : "_No frequently missed quiz questions in this period._"}

---

_This report was generated by Arcademy staff. Metrics are aggregated; no individual wallet addresses are included._
`;
}

export function ecosystemReportToCsv(overview: EcosystemOverview): string {
  const escape = (value: string) => `"${value.replace(/"/g, '""')}"`;
  const lines: string[] = [];

  lines.push("section,name,value,extra");
  for (const entry of overview.scorecard) {
    lines.push(
      `scorecard,${escape(entry.label)},${escape(entry.value)},${escape(`target ${entry.target}`)}`
    );
  }
  for (const step of overview.funnel) {
    lines.push(
      `funnel,${escape(step.label)},${step.count},${
        step.rateFromPrevious != null ? `${step.rateFromPrevious}%` : ""
      }`
    );
  }
  for (const p of overview.products) {
    lines.push(
      `project,${escape(p.productName)},${p.starts},${escape(
        `badges ${p.badgeAwards}; completion ${p.completionRate != null ? `${p.completionRate}%` : "n/a"}`
      )}`
    );
  }
  return lines.join("\n");
}
